name: eling_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^13.2.0
  flutter_riverpod: ^2.6.1
  flutter_ui:
    path: /home/nov/Projects/flutter_ui/flutter_ui
  flutter_screenutil: ^5.9.3
  formz: ^0.8.0
  flutter_gen: ^5.10.0
  freezed_annotation: ^2.4.4
  logger: ^2.5.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  sqflite_common_ffi: ^2.3.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.7
  json_serializable: ^6.9.5


flutter:

  uses-material-design: true




